#!/usr/bin/env python
"""
Example: Generate a storyboard without creating videos.

This is useful for:
1. Previewing what videos will be generated
2. Testing different prompts quickly
3. Manually editing storyboards before generation
"""
import sys
import json
from video_engine.llm.storyboard_generator import StoryboardGenerator
from video_engine import config


def main():
    """Generate and display a storyboard."""
    # Check API key
    api_keys = config.validate_api_keys()

    if not api_keys.get("anthropic"):
        print("Error: ANTHROPIC_API_KEY not configured")
        return 1

    print("=" * 60)
    print("Storyboard Generation Example")
    print("=" * 60)
    print()

    # Define prompt
    prompt = "A journey through space: launching from Earth, traveling through the solar system, arriving at a distant galaxy"

    print(f"Prompt: {prompt}")
    print()

    try:
        # Create generator
        generator = StoryboardGenerator(llm="claude")

        # Generate storyboard
        print("Generating storyboard with Claude...")
        storyboard = generator.generate(
            user_prompt=prompt,
            max_shots=5,
        )

        print("✓ Storyboard generated")
        print()

        # Display results
        print("=" * 60)
        print(f"Title: {storyboard.title}")
        print("=" * 60)
        print()

        print(f"Total Duration: {storyboard.total_duration_seconds:.1f} seconds")
        print(f"Number of Shots: {storyboard.shot_count}")
        print(f"Generated by: {storyboard.generated_by}")
        print()

        if storyboard.style:
            print("Style:")
            for key, value in storyboard.style.items():
                print(f"  {key}: {value}")
            print()

        print("Shots:")
        print("-" * 60)

        for shot in storyboard.shots:
            print()
            print(f"Shot {shot.sequence_number}: {shot.description}")
            print(f"  Duration: {shot.duration_seconds}s")
            print(f"  Camera: {shot.camera_movement}, {shot.camera_angle}")
            print(f"  Motion: {shot.motion_intensity:.1f}")
            print(f"  Prompt: {shot.text_prompt}")

        print()
        print("-" * 60)

        # Optionally save to JSON
        save = input("\nSave storyboard to JSON? (y/n): ").lower()

        if save == 'y':
            filename = f"storyboard_{storyboard.id}.json"

            with open(filename, 'w') as f:
                json.dump(storyboard.model_dump(), f, indent=2, default=str)

            print(f"Saved to: {filename}")

        return 0

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
