/**
 * Storyboard viewer component
 */
import React from 'react';
import {
  Box,
  Paper,
  Typography,
  Card,
  CardContent,
  Chip,
} from '@mui/material';
import {
  Videocam as VideocamIcon,
  Timer as TimerIcon,
} from '@mui/icons-material';
import type { Storyboard } from '../types/api';

interface StoryboardViewerProps {
  storyboard: Storyboard | null;
}

const StoryboardViewer: React.FC<StoryboardViewerProps> = ({ storyboard }) => {
  if (!storyboard) {
    return (
      <Paper elevation={3} sx={{ p: 3, textAlign: 'center' }}>
        <Typography color="text.secondary">
          Storyboard will appear here after generation starts
        </Typography>
      </Paper>
    );
  }

  return (
    <Paper elevation={3} sx={{ p: 3 }}>
      <Box sx={{ mb: 3 }}>
        <Typography variant="h6" gutterBottom>
          {storyboard.title}
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          {storyboard.user_prompt}
        </Typography>
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Chip
            icon={<VideocamIcon />}
            label={`${storyboard.shot_count} shots`}
            size="small"
          />
          <Chip
            icon={<TimerIcon />}
            label={`${storyboard.total_duration_seconds.toFixed(1)}s`}
            size="small"
          />
          <Chip
            label={`Generated by ${storyboard.generated_by}`}
            size="small"
            variant="outlined"
          />
        </Box>
      </Box>

      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2 }}>
        {storyboard.shots.map((shot) => (
          <Card key={shot.id} variant="outlined">
            <CardContent>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                <Typography variant="subtitle2" color="primary">
                  Shot {shot.sequence_number}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {shot.duration_seconds}s
                </Typography>
              </Box>

              <Typography variant="body2" paragraph>
                {shot.description}
              </Typography>

              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: 1 }}>
                {shot.camera_movement && (
                  <Chip
                    label={shot.camera_movement}
                    size="small"
                    variant="outlined"
                  />
                )}
                {shot.camera_angle && (
                  <Chip
                    label={shot.camera_angle}
                    size="small"
                    variant="outlined"
                  />
                )}
              </Box>

              <Typography variant="caption" color="text.secondary" sx={{ fontStyle: 'italic' }}>
                "{shot.text_prompt}"
              </Typography>
            </CardContent>
          </Card>
        ))}
      </Box>
    </Paper>
  );
};

export default StoryboardViewer;
